on:
  push

env:
  sql_server: mysql12-dataserver
  database_name: db1
  resource-group: myresourcegroup5
  location: centralus
  admin-user: harry
  admin-password: ret90@367
  sql_command: "show databases"

jobs:
  cleanup_resources:
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Clean up resources
        run: |
          az group delete --name $resource-group --yes
          
  deploy_resources:
    runs-on: ubuntu-latest
    needs: cleanup_resources
    steps:     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Create Azure SQL Server
        run: |
          az sql server create --name $sql_server --resource-group $resource-group --location $location --admin-user $admin-user --admin-password $admin-password
          az sql server firewall-rule create --resource-group $resource-group --server $sql_server -n AllowYourIp --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0

      - name: Create Azure SQL Database
        run: |
          az sql db create --name $database_name --resource-group $resource-group --server $sql_server --sample-name AdventureWorksLT --edition GeneralPurpose --family Gen5 --capacity 2

      - name: Connect to Azure SQL Database
        run: sqlcmd -S tcp:$sql_server.database.windows.net -d db1 -U $admin-user -P $admin-password -Q $sql_command"
