on:
  push

jobs:
  cleanup_resources:
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Clean up resources
        run: |
          az sql db delete --name db1 --server mysql12 --resource-group "myresourcegroup5" --yes
          az sql server delete --name mysql12 --resource-group "myresourcegroup5" --yes
          
  deploy_resources:
    runs-on: ubuntu-latest
    needs: cleanup_resources
    steps:     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Create Azure SQL Server
        run: az sql server create --name mysql12 --resource-group "myresourcegroup5" --location centralus --admin-user harry --admin-password ret90@367

      - name: Create Azure SQL Database
        run: az sql db create --name db1 --resource-group "myresourcegroup5" --server mysql12 --database-edition "Basic"

      - name: Get connection string
        id: connection-string
        run: |
          echo "connection_string=$(az sql db show-connection-string --server mysql12 --name db1 --client ado.net)"
    #outputs:
     # connection_string1: ${{ steps.connection-string.outputs.connection_string }}
    
      - name: Connect to Azure SQL Database
        run: sqlcmd -S tcp:mysql12.database.windows.net -d db1 -U harry -P ret90@367 -Q "show database;"
